severity: low
exclude:
  - message: Dependencies
    paths:
      - node_modules
      - venv

  - message: Build outputs
    paths:
      - build
      - coverage
      - dist

  - message: Tooling outputs
    paths:
      - .DS_Store
      - yarn-error.log
      - yarn.lock
